# Letsencrypt-specific configuration:

- name: Setup letsencrypt-specific configuration files
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root group=root mode={{ item.mode }}
  with_items:
    - { src: 'nginx_letsencrypt.conf.j2', dest: '{{ nginx_conf_directory }}/letsencrypt.conf', mode: "u=rw,g=r,o=r" }
  notify:
    - restart nginx

- meta: flush_handlers

- name: Create letsencrypt user account key
  shell: openssl genrsa 4096 > "{{ letsencrypt_user_account_private_key  }}" creates="{{ letsencrypt_user_account_private_key }}"

- name: create http-01 domain key
  command: openssl genrsa -out {{ domain_key }}.http-01 4096
  args:
    creates: "{{ domain_key }}.http-01"

- name: create http-01 challenge single domain csr
  command: openssl req -new -sha256 -key {{ domain_key }}.http-01 -subj "{{ cert_subject }}" -out {{ domain_csr }}.http-01
  args:
    creates: "{{ domain_csr }}.http-01"

- name: start Let's Encrypt http-01 challenge
  letsencrypt:
    account_key: "{{ account_key }}"
    csr: "{{ domain_csr }}.http-01"
    dest: "{{ domain_crt }}.http-01"
    challenge: http-01
    acme_directory: "{{ acme_directory }}"
  register: letsencrypt

- set_fact:
    challenge_file: /etc/letsencrypt/{{ letsencrypt['challenge_data'][domain_hostname]['http-01']['resource'] }}
    challenge_value: "{{ letsencrypt['challenge_data'][domain_hostname]['http-01']['resource_value'] }}"
  when: letsencrypt|changed

- name: create http-01 challenge directory
  file:
    path: "{{ challenge_file|dirname }}"
    state: directory
  when: letsencrypt|changed

- name: create the http-01 challenge file
  copy:
    dest: "{{ challenge_file }}"
    content: "{{ challenge_value }}"
  when: letsencrypt|changed

- name: Finalize http-01 challenge
  letsencrypt:
    account_key: "{{ account_key }}"
    csr: "{{ domain_csr }}.http-01"
    dest: "{{ domain_crt }}.http-01"
    data: "{{ letsencrypt }}"
    challenge: http-01
    acme_directory: "{{ acme_directory }}"
  register: letsencrypt
  notify:
    - restart nginx
  when: letsencrypt|changed

- name: Copy signed certificates to correct location
  copy: remote_src=True src={{ item.src }} dest={{ item.dest }}
  with_items:
   - { 'src': "{{ domain_crt }}.http-01", 'dest': "{{ nginx_ssl_certificate }}" }
   - { 'src': "{{ domain_key }}.http-01", 'dest': "{{ nginx_ssl_certificate_key }}" }
  when: letsencrypt|changed

- meta: flush_handlers
