# Letsencrypt-specific configuration:

- name: Create letsencrypt user account key
  shell: openssl genrsa 4096 > "{{ letsencrypt_user_account_private_key  }}" creates="{{ letsencrypt_user_account_private_key }}"

- name: Create letsencrypt user account public key
  shell: openssl rsa -in "{{ letsencrypt_user_account_private_key  }}" -pubout > "{{ letsencrypt_user_account_public_key }}" creates="{{ letsencrypt_user_account_public_key }}"

- name: Create domain key for {{ galaxy_extras_galaxy_domain  }}  # For initial challenge need either http-only or self-signed
  shell: openssl genrsa 4096 > "{{ nginx_ssl_certificate_key }}" creates="{{ nginx_ssl_certificate_key }}"

- name: Create CSR for {{ galaxy_extras_galaxy_domain }}
  shell: openssl req -new -sha256 -key "{{ nginx_ssl_certificate_key }}" -subj "/CN={{ galaxy_extras_galaxy_domain }}" > {{ galaxy_extras_letsencrypt_csr }}

- name: letsencrypt ACME challenge
  letsencrypt:
    account_key: "{{ letsencrypt_user_account_private_key }}"
    csr: "{{ galaxy_extras_letsencrypt_csr }}"
    dest: "{{ nginx_ssl_certificate }}"
  register: letsencrypt_challenge

- debug: var=letsencrypt_challenge

- name: Create letsencrypt wellknown directory
  file: path=/etc/letsencrypt/wellknown state=directory mode=0755

- copy:
    dest: /etc/letsencrypt/wellknown/{{ item['http-01']['resource'] }}
    content: "{{ item['http-01']['resource_value'] }}"
    items: "{{ letsencrypt_challenge['challenge_data']"
    when: letsencrypt_challenge|changed

- letsencrypt:
    account_key: "{{ letsencrypt_user_account_private_key }}"
    csr: "{{ galaxy_extras_letsencrypt_csr }}"
    dest: "{{ nginx_ssl_certificate }}"
    data: "{{ letsencrypt_challenge }}"
