# Letsencrypt-specific configuration:

- name: create http-01 domain key
  command: openssl genrsa -out {{ domain_key }}.http-01 4096
  args:
    creates: "{{ domain_key }}.http-01"

- name: create http-01 challenge single domain csr
  command: openssl req -new -sha256 -key {{ domain_key }}.http-01 -subj "{{ cert_subject }}" -out {{ domain_csr }}.http-01
  args:
    creates: "{{ domain_csr }}.http-01"

- name: start Let's Encrypt http-01 challenge
  letsencrypt:
    account_key: "{{ account_key }}"
    csr: "{{ domain_csr }}.http-01"
    dest: "{{ domain_crt }}.http-01"
    challenge: http-01
  register: letsencrypt

- set_fact:
    challenge_file: /var/www/html/{{ letsencrypt['challenge_data'][domain_hostname]['http-01']['resource'] }}
    challenge_value: "{{ letsencrypt['challenge_data'][domain_hostname]['http-01']['resource_value'] }}"

- name: create http-01 challenge directory
  file:
    path: "{{ challenge_file|dirname }}"
    state: directory

- name: create the http-01 challenge file
  copy:
    dest: "{{ challenge_file }}"
    content: "{{ challenge_value }}"

- name: Finalize http-01 challenge
  letsencrypt:
    account_key: "{{ account_key }}"
    csr: "{{ domain_csr }}.http-01"
    dest: "{{ domain_crt }}.http-01"
    data: "{{ letsencrypt }}"
    challenge: http-01
  register: letsencrypt